Default: &defaults
  database: HaskellWebapp.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: HaskellWebapp_test.sqlite3
  <<: *defaults

Staging:
  database: HaskellWebapp_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: HaskellWebapp_production.sqlite3
  poolsize: 100
  <<: *defaults
